### PR TITLE
new maintainer for liushuo

### PR DESCRIPTION
**Pull request by ls-2018**
Apply to be maintainer. Contributions are shown in the link:
- https://github.com/openkruise/kruise/issues?q=involves%3Als-2018+
- https://github.com/openkruise/openkruise.io/pulls?q=involves%3Als-2018+
- https://github.com/openkruise/rollouts/pulls?q=involves%3Als-2018+

### CODE REVIEW

**Comment by zmberg** [comment]
+1 @ls-2018  has been very active in the kruise community for the past year, and has made a lot of very meaningful PRs, and the quality of the code completion is relatively good, so I personally agree to become a maintainer.

**Comment by furykerry** [comment]
+1 welcome @ls-2018

**Comment by FillZpp** [comment]
+1 welcome!

**Pull request merged**
