### PR TITLE
New maintainer for hantmac

### PR DESCRIPTION
**Pull request by hantmac**
Apply to be maintainer

### CODE REVIEW

**Comment by hantmac** [comment]
[This PR](https://github.com/kubernetes-sigs/krew-index/pull/1809) need the maintainer info.

**Comment by FillZpp** [comment]
+1

Shanjie Han is a senior member of OpenKruise. He set up kruise-tools, continuously work on it, and guide students in summer of code. Thanks for all his contribution.

**Comment by furykerry** [comment]
+1 

Shanjie Han has been actively participated in the community meeting and Dingding channel, he is the major maintainer behind kruise-tools and set up [triton](https://github.com/triton-io) to solve end to end user problem in app delivery using OpenKruise. Thanks for all his contribution.

**Comment by Fei-Guo** [comment]
+1. welcome.

**Pull request merged**
